# Generated by Django 5.0.1 on 2024-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('git_hub_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.CharField(default='Portfolio project', max_length=50)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField()),
                ('image_title', models.ImageField(default='portfolio/title-default_project_img.png', upload_to='portfolio/')),
                ('image_main', models.ImageField(default='portfolio/main-default_project_img.png', upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_of_knowledge', models.SmallIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
