# Generated by Django 5.0.1 on 2024-09-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutme_leet_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='leet_code',
            new_name='leet_code_url',
        ),
    ]
