# Generated by Django 5.0.1 on 2024-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_leet_code_aboutme_leet_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_main',
            field=models.ImageField(default='portfolio/default_project_img.png', upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_title',
            field=models.ImageField(default='portfolio/default_project_img.png', upload_to='portfolio/'),
        ),
    ]
