# Generated by Django 5.0.1 on 2024-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projects_created_date_alter_projects_image_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='view_portfolio_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
