# Generated by Django 5.0.1 on 2024-10-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rezume_link_for_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
